{
 "title": "Crawler",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "crawler_page_parse_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "crawler_page_parse_time_bucket" }
   ]
  },
  {
   "title": "web_pages_served",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "web_pages_served" }
   ]
  },
  {
   "title": "crawler_pages_parsed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "crawler_pages_parsed" }
   ]
  },
  {
   "title": "web_page_gen_time_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "web_page_gen_time_count" }
   ]
  }
 ]
}